[profile.default]
src = "src"
out = "artifacts"
libs = ["node_modules", "lib"]
remappings = [
    "@ensdomains/=node_modules/@ensdomains/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "hardhat/=node_modules/hardhat/",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
astar = "${ASTAR_RPC_URL}"
bsc = "${BSC_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
localhost = "${LOCALHOST}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }