[profile.default]
optimizer = true
optimizer_runs = 200
src = "src"
out = "out"
libs = ["lib"]
build_info = true
extra_output = ["storageLayout"]
evm_version = "shanghai"
solc_version = "0.8.20"
auto_detect_solc = true
fs_permissions = [{access = "read-write", path = "./"}]

[fmt]
multiline_func_header = "all"
number_underscore = "thousands"
wrap_comments = true


remappings = [
	"@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
	"@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
	"openzeppelin-foundry-upgrades/=lib/openzeppelin-foundry-upgrades/src/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
